version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run: echo "If you can see this message, I've been triggered on the main branch"
            
workflows:
  build-workflow:
    jobs:
      - build
